name: vpr-sota
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  - numpy
  - pandas
  - opencv
  - pillow
  - matplotlib
  - seaborn
  - scikit-learn
  - tqdm
  - tensorboard
  - einops
  - timm
  - albumentations
  - scipy
  - h5py
  - faiss-gpu
  - pip
  - pip:
    - transformers
    - open_clip_torch
    - kornia
    - gdown
    - wandb
    - prettytable
    - yacs
