# DELG (Deep Local and Global features) Configuration

# Model settings
backbone: "resnet50"
global_dim: 2048
local_dim: 128
num_keypoints: 1000
pretrained: true

# Dataset settings
train_csv: "/media/pragyan/Data/racecar_ws/output/sequences/M-SOLO-SLOW-70-100/poses/poses.csv"
test_csv: "/media/pragyan/Data/racecar_ws/output/sequences/M-MULTI-SLOW-KAIST/poses/poses.csv"
train_base_path: "/media/pragyan/Data/racecar_ws/output/sequences/M-SOLO-SLOW-70-100/images/"
test_base_path: "/media/pragyan/Data/racecar_ws/output/sequences/M-MULTI-SLOW-KAIST/images/"
camera_filter: "front_left_center"
image_size: 224

# GPS settings
positive_threshold: 5  # meters
negative_threshold: 25  # meters

# Training settings
batch_size: 8  # Smaller batch size due to dual feature extraction
num_epochs: 50
learning_rate: 0.0001
weight_decay: 0.0001
num_workers: 4
device: "cuda"

# Loss settings
margin: 0.1
alpha: 1.0  # Weight for global loss
beta: 0.5   # Weight for local loss

# Learning rate schedule
lr_step_size: 20
lr_gamma: 0.5

# Evaluation settings
eval_every: 5
recall_k_values: [1, 5, 10]
distance_threshold: 5  # meters

# Logging and saving
log_interval: 100
save_every_n_epochs: 10
output_dir: "experiments/delg_output"

# Mixed precision training
mixed_precision: true

# Output settings
early_stopping_patience: 10
gradient_accumulation_steps: 1

# Data augmentation (handled by transforms)
random_flip: true
color_jitter: true
