# EigenPlaces Configuration

# Model settings
backbone: "resnet50"
output_dim: 2048
eigen_scales: [1, 2, 4]  # Multi-scale eigenvalue decomposition
pretrained: true

# Dataset settings
train_csv: "/media/pragyan/Data/racecar_ws/output/sequences/M-SOLO-SLOW-70-100/poses/poses_minimal_coverage_0.5m.csv"
test_csv: "/media/pragyan/Data/racecar_ws/output/sequences/M-MULTI-SLOW-KAIST/poses/poses.csv"
train_base_path: "/media/pragyan/Data/racecar_ws/output/sequences/M-SOLO-SLOW-70-100/images/"
test_base_path: "/media/pragyan/Data/racecar_ws/output/sequences/M-MULTI-SLOW-KAIST/images/"
camera_filter: "front_left_center"
image_size: 224

# GPS settings
positive_threshold: 5  # meters
negative_threshold: 25  # meters

# Training settings
batch_size: 16
num_epochs: 50
learning_rate: 0.001
weight_decay: 0.0001
num_workers: 4
device: "cuda"

# Loss settings
loss_type: "viewpoint_contrastive"  # "triplet" or "viewpoint_contrastive"
margin: 0.1
temperature: 0.07
viewpoint_weight: 0.1  # Weight for viewpoint regularization

# Learning rate schedule
lr_step_size: 20
lr_gamma: 0.5

# Evaluation settings
eval_every: 5
recall_k_values: [1, 5, 10]
distance_threshold: 5  # meters

# Logging and saving
log_interval: 100
save_every_n_epochs: 10
output_dir: "experiments/eigenplaces_output"

# Mixed precision training
mixed_precision: true
gradient_accumulation_steps: 1

# Output settings
early_stopping_patience: 10
gradient_accumulation_steps: 1
